import { Providers } from "@/components/Provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// i am usig javascript to appeir a dn disappeir an element but it's sometime creating a overflow which i am not able to hide
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark w-screen h-screen`}><Providers>{children}</Providers></body>
    </html>
  );
}
